[application]
name = "website"
out_dir = "dist"
asset_dir = "public"
default_platform = "web"

[web.resource]
style = ["/tailwind.css", "/style.css", "/hljs/styles/atom-one-dark.min.css"]
script = ["/hljs/highlight.min.js", "/riscvasm.min.js"]

[web.app]
title = "Alessandra Simmons"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource.dev]
script = []