[application]
name = "website"
out_dir = "dist"
asset_dir = "public"
default_platform = "web"

[web.resource]
style = ["/tailwind.css", "/style.css", "/hljs/styles/atom-one-dark.css"]
script = ["/hljs/highlight.min.js", "/riscvasm.min.js"]

[web.app]

# HTML title tag content
title = "{{project-name}}"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []